services:
  node1:
    image: p2pfl-deploy
    container_name: node1
    networks:
      p2pfl-net:
        ipv4_address: 172.20.0.2
    ports:
      - "8001:8000"
    command: >
      python p2pfl/examples/node_api_combined.py --host 172.20.0.2 --port 5001 --wait_peers 2 --api_port 8000

  node2:
    image: p2pfl-deploy
    container_name: node2
    depends_on:
      - node1
    networks:
      p2pfl-net:
        ipv4_address: 172.20.0.3
    ports:
      - "8002:8000"
    command: >
      python p2pfl/examples/node_api_combined.py --host 172.20.0.3 --port 5002 --connect 172.20.0.2:5001 --api_port 8000

  node3:
    image: p2pfl-deploy
    container_name: node3
    depends_on:
      - node1
    networks:
      p2pfl-net:
        ipv4_address: 172.20.0.4
    ports:
      - "8003:8000"
    command: >
      python p2pfl/examples/node_api_combined.py --host 172.20.0.4 --port 5003 --connect 172.20.0.2:5001 --api_port 8000

networks:
  p2pfl-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
